<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">

  <PropertyGroup>
    <Version>1.0.0</Version>
    <PackageProjectUrl>https://github.com/AlessHub/Mount-Select</PackageProjectUrl>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <OutputPath>$(AppData)\XIVLauncher\devPlugins\MountSelect\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="System" />
  </ItemGroup>

  <ItemGroup>
    <None Include="icon.png" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Data\mounts.json" />
  </ItemGroup>

</Project>